---
- name: Configure Hosts | Install delphix.configure-workshop-hosts
  shell: |
    ansible-galaxy install git+https://github.com/delphix/delphix.configure-workshop-hosts.git
  args:
    creates: "{{ ansible_env.HOME }}/.ansible/roles/delphix.configure-workshop-hosts"
  become: no
- name: Install python-netaddr
  yum:
    name: python-netaddr
    state: present
  become: yes
- name: Ensures /etc/ansible dir exists
  file:
    path: /etc/ansible
    state: directory
  become: yes
- name: create /etc/ansible/hosts
  copy:
    src: hosts
    dest: /etc/ansible/hosts
  become: yes
- name: create configure_hosts.yml
  copy:
    src: configure_hosts.yml
    dest: /etc/ansible/configure_hosts.yml
  become: yes
- name: "Create {{ ansible_env.HOME }}/startup.sh"
  copy:
    src: startup.sh
    dest: "{{ ansible_env.HOME }}/startup.sh"
    mode: "u+x,g+x"
  become: no
- name: Creates the reboot crontab for WAIT/READY
  cron:
    name: "Update the /etc/hosts file on boot"
    special_time: reboot
    job: "{{ ansible_env.HOME }}/startup.sh"
  become: no
- name: Configure Hosts | Register network as the /24 network
  shell: |
    set -o pipefail
    STUDENT=$(echo {{ ansible_default_ipv4.address }} | cut -d. -f3)
    echo "10.0.${STUDENT}.0"
  args:
    executable: /bin/bash
  register: network
  become: yes
  changed_when: false
- name: Configure Hosts | Echo network.stdout
  debug:
    msg: "This network is {{ network.stdout }}"
- name: Configure Hosts | set hosts_file as /etc/hosts for VM
  set_fact:
    hosts_file: /etc/hosts
  when: not in_container
- name: Configure Hosts | set hosts_file as /tmp/hosts for molecule container
  set_fact:
    # we just test the creation of the file
    hosts_file: /tmp/hosts
  when: in_container
  changed_when: false
- name: "Configure Hosts | create {{ hosts_file }} for molecule container"
  file:
    state: touch
    path: "{{ hosts_file }}"
  register: file_created
  changed_when: file_created.changed == "true"
- debug:
    msg: "{{ file_created }}"
- name: "Configure Hosts | Add mappings to {{ hosts_file }}"
  blockinfile:
    path: "{{ hosts_file }}"
    block: |
      {{ network.stdout | ipmath(item.last_octet) }}  {{ item.name }} {{ item.name }}.{{ domain_suffix }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  loop: "{{ lab_systems }}"
  become: yes
