#
# Copyright (c) 2018 by Delphix. All rights reserved.
#
---

extends: default

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  line-length: disable
  truthy: {allowed-values: ["true", "false", "yes", "no"]}
