#
# Copyright (c) 2011, 2019 by Delphix. All rights reserved.
#
---
  - name: Configure Hosts | Configure the /etc/hosts file to contain local env information
    hosts: all
    become: yes
    vars:
    roles:
      - role: delphix.configure-workshop-hosts
